server:
  port: 8083
spring:
  application:
    name: drone-app
  datasource:
    url: jdbc:h2:mem:drone
    driver-class-name: org.h2.Driver
    username: musalasoft
    password: musalasoft
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  file:
    name: logs/drone_api.log

